[[hooks]]
stage = "build"
command = "tailwindcss"
command_arguments = [
    "build",
    "-i",
    "index.css",
    "-o",
    "dist/.stage/tailwind.css",
]
[[proxy]]
rewrite = "/api/v1/"
backend = "http://localhost:8080/"